alter table public.media_items
  drop constraint media_items_source_identity_check,
  add constraint media_items_source_identity_check check (
    (source_type = 'youtube' and source_url is null and youtube_video_id = pg_catalog.btrim(youtube_video_id) and youtube_video_id ~ '^[A-Za-z0-9_-]{11}$' and torrent_info_hash is null and torrent_input_kind is null and torrent_magnet_uri is null and torrent_metadata_path is null and torrent_name is null and torrent_file_index is null and torrent_file_path is null and torrent_file_name is null and torrent_file_size is null)
    or (source_type in ('torrent','local_p2p') and source_url is null and youtube_video_id is null and torrent_info_hash = pg_catalog.lower(pg_catalog.btrim(torrent_info_hash)) and torrent_info_hash ~ '^[a-f0-9]{40}$' and torrent_input_kind = 'magnet' and torrent_magnet_uri = pg_catalog.btrim(torrent_magnet_uri) and pg_catalog.char_length(torrent_magnet_uri) between 20 and 16384 and torrent_magnet_uri like 'magnet:?%' and torrent_metadata_path is null and torrent_file_index >= 0 and torrent_file_path = pg_catalog.btrim(torrent_file_path) and pg_catalog.char_length(torrent_file_path) between 1 and 1024 and torrent_file_path !~ '(^|/)\.\.(/|$)' and torrent_file_name = pg_catalog.btrim(torrent_file_name) and pg_catalog.char_length(torrent_file_name) between 1 and 255 and torrent_file_size >= 0 and (source_type = 'torrent' or torrent_file_size > 0))
    or (source_type = 'torrent' and source_url is null and youtube_video_id is null and torrent_info_hash = pg_catalog.lower(pg_catalog.btrim(torrent_info_hash)) and torrent_info_hash ~ '^[a-f0-9]{40}$' and torrent_input_kind = 'torrent_file' and torrent_magnet_uri is null and torrent_metadata_path = 'rooms/' || room_id::text || '/media/' || id::text || '/' || torrent_info_hash || '.torrent' and torrent_file_index >= 0 and torrent_file_path = pg_catalog.btrim(torrent_file_path) and pg_catalog.char_length(torrent_file_path) between 1 and 1024 and torrent_file_path !~ '(^|/)\.\.(/|$)' and torrent_file_name = pg_catalog.btrim(torrent_file_name) and pg_catalog.char_length(torrent_file_name) between 1 and 255 and torrent_file_size >= 0)
    or (source_type not in ('youtube','torrent','local_p2p') and source_url is not null and source_url = pg_catalog.btrim(source_url) and pg_catalog.char_length(source_url) between 1 and 4096 and youtube_video_id is null and torrent_info_hash is null and torrent_input_kind is null and torrent_magnet_uri is null and torrent_metadata_path is null and torrent_name is null and torrent_file_index is null and torrent_file_path is null and torrent_file_name is null and torrent_file_size is null)
  );

drop function if exists public.add_local_p2p_media_item(uuid, text, uuid, text, text, text, bigint);
drop function if exists public.edit_local_p2p_media_item(uuid, uuid, text, text, text, text, bigint);
drop function if exists public.get_local_p2p_source(uuid, uuid);

create function public.add_local_p2p_media_item(p_room_id uuid,p_title text,p_media_id uuid,p_info_hash text,p_magnet_uri text,p_file_name text,p_file_size bigint)
returns setof public.media_items language plpgsql security definer set search_path=''
as $$ declare v_room public.rooms%rowtype; v_title text:=pg_catalog.btrim(p_title); v_hash text:=pg_catalog.lower(pg_catalog.btrim(p_info_hash)); v_magnet text:=pg_catalog.btrim(p_magnet_uri); v_name text:=pg_catalog.btrim(p_file_name); v_count integer; v_pos integer;
begin v_room:=private.lock_owned_room(p_room_id); if p_media_id is null or v_title is null or pg_catalog.char_length(v_title) not between 1 and 200 or v_hash !~ '^[a-f0-9]{40}$' or v_magnet not like 'magnet:?%' or pg_catalog.char_length(v_magnet) not between 20 and 16384 or pg_catalog.strpos(pg_catalog.lower(v_magnet),'xt=urn:btih:'||v_hash)=0 or v_name is null or pg_catalog.char_length(v_name) not between 1 and 255 or v_name like '%/%' or v_name like '%\\%' or p_file_size is null or p_file_size<=0 then raise exception using errcode='22023',message='Local P2P media requires a valid generated descriptor'; end if; select count(*)::integer,coalesce(pg_catalog.max(queue_position)+1,0) into v_count,v_pos from public.media_items where room_id=v_room.id; if v_count>=500 then raise exception using errcode='22023',message='The room queue cannot contain more than 500 media items'; end if; return query insert into public.media_items(id,room_id,title,source_url,source_type,youtube_video_id,queue_position,created_by,torrent_info_hash,torrent_input_kind,torrent_magnet_uri,torrent_metadata_path,torrent_name,torrent_file_index,torrent_file_path,torrent_file_name,torrent_file_size) values(p_media_id,v_room.id,v_title,null,'local_p2p',null,v_pos,auth.uid(),v_hash,'magnet',v_magnet,null,v_name,0,v_name,v_name,p_file_size) returning *; end; $$;

create function public.edit_local_p2p_media_item(p_room_id uuid,p_media_id uuid,p_title text,p_info_hash text,p_magnet_uri text,p_file_name text,p_file_size bigint)
returns setof public.media_items language plpgsql security definer set search_path=''
as $$ declare v_title text:=pg_catalog.btrim(p_title); v_hash text:=pg_catalog.lower(pg_catalog.btrim(p_info_hash)); v_magnet text:=pg_catalog.btrim(p_magnet_uri); v_name text:=pg_catalog.btrim(p_file_name);
begin perform private.lock_owned_room(p_room_id); if p_media_id is null or v_title is null or pg_catalog.char_length(v_title) not between 1 and 200 or v_hash !~ '^[a-f0-9]{40}$' or v_magnet not like 'magnet:?%' or pg_catalog.char_length(v_magnet) not between 20 and 16384 or pg_catalog.strpos(pg_catalog.lower(v_magnet),'xt=urn:btih:'||v_hash)=0 or v_name is null or pg_catalog.char_length(v_name) not between 1 and 255 or v_name like '%/%' or v_name like '%\\%' or p_file_size is null or p_file_size<=0 then raise exception using errcode='22023',message='Local P2P media requires a valid generated descriptor'; end if; return query update public.media_items set title=v_title,source_url=null,source_type='local_p2p',youtube_video_id=null,torrent_info_hash=v_hash,torrent_input_kind='magnet',torrent_magnet_uri=v_magnet,torrent_metadata_path=null,torrent_name=v_name,torrent_file_index=0,torrent_file_path=v_name,torrent_file_name=v_name,torrent_file_size=p_file_size where room_id=p_room_id and id=p_media_id returning *; if not found then raise exception using errcode='P0002',message='Media item was not found in the room'; end if; end; $$;

create function public.get_local_p2p_source(p_room_id uuid,p_media_id uuid)
returns table(info_hash text,magnet_uri text,file_name text,file_size bigint) language plpgsql stable security definer set search_path=''
as $$ declare v_user uuid:=auth.uid(); v_owner boolean; v_current uuid;
begin if v_user is null then raise exception using errcode='42501',message='Authentication is required'; end if; select owner_user_id=v_user,ps.current_media_id into v_owner,v_current from public.rooms r join public.room_playback_state ps on ps.room_id=r.id where r.id=p_room_id and (r.owner_user_id=v_user or exists(select 1 from public.room_sessions s where s.room_id=r.id and s.user_id=v_user)); if not found then raise exception using errcode='42501',message='Room membership is required'; end if; if not v_owner and v_current is distinct from p_media_id then raise exception using errcode='42501',message='Viewers may resolve only the current media'; end if; return query select torrent_info_hash,torrent_magnet_uri,torrent_file_name,torrent_file_size from public.media_items where room_id=p_room_id and id=p_media_id and source_type='local_p2p'; if not found then raise exception using errcode='P0002',message='Local P2P media was not found'; end if; end; $$;

revoke all on function public.add_local_p2p_media_item(uuid,text,uuid,text,text,text,bigint),public.edit_local_p2p_media_item(uuid,uuid,text,text,text,text,bigint),public.get_local_p2p_source(uuid,uuid) from public,anon,authenticated;
grant execute on function public.add_local_p2p_media_item(uuid,text,uuid,text,text,text,bigint),public.edit_local_p2p_media_item(uuid,uuid,text,text,text,text,bigint),public.get_local_p2p_source(uuid,uuid) to authenticated;
