/** Pure torrent rules and value objects. This module is safe for browser and server use. */
export {
  TORRENT_MANIFEST_MAX_FILES,
  TORRENT_MANIFEST_PAGE_SIZE,
  TORRENT_METADATA_MAX_BYTES,
  TORRENT_PATH_MAX_DEPTH,
  TORRENT_PATH_MAX_LENGTH,
  TorrentGatewayError,
  type PrepareTorrentInput,
  type ResolvedTorrentPlaybackSource,
  type TorrentAudioTrack,
  type TorrentEmbeddedSubtitle,
  type TorrentErrorCategory,
  type TorrentFileKind,
  type TorrentGateway,
  type TorrentGatewayInput,
  type TorrentInspection,
  type TorrentInspectionStatus,
  type TorrentManifestFile,
  type TorrentMediaProbe,
  type TorrentStatusInput,
  type TorrentGatewayStatus,
  type ResolveTorrentPlaybackInput,
  type TorrentInputKind,
} from "../torrent-contracts";
export {
  WEBTOR_AUTOSELECT_FILE_PATH,
  canonicalMagnetUri,
  classifyTorrentFile,
  defaultSubtitleFileIndexes,
  extractInfoHashFromTorrentInput,
  inspectionFromMagnetIdentity,
  isWebtorAutoselectPath,
  normalizeTorrentPath,
  parseMagnetIdentity,
  parseTorrentFileIdentity,
  rankSubtitleCandidates,
  rankVideoCandidates,
  type ParsedTorrentIdentity,
  type SubtitleCandidate,
} from "../torrent-manifest";
